# Generated by Django 6.0.6 on 2026-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webtintuc', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
